# .github/workflows/publish-docker.yml

name: Publish Docker Image

# Run this workflow on every push to your main branch
on:
  push:
    branches: [ "master" ] # Change to "main" if that's your default branch

jobs:
  build-and-push:
    # Use the latest version of Ubuntu to run the job
    runs-on: ubuntu-latest
    # Grant permissions for the job to write to the GitHub Package Registry
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checks out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up QEMU for multi-platform build emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Sets up Docker Buildx, the builder that can create multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Logs into the GitHub Container Registry using the secret you created
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 5. Extracts useful metadata like image tags
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # 6. Builds the image from your Dockerfile and pushes it to GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}